# Generated by Django 4.0 on 2021-12-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_body_comments_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
